services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: email_validator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - evnet

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    networks:
      - evnet

  redis:
    image: redis:7
    networks:
      - evnet

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn email_validator.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_DB=email_validator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - evnet

  worker:
    build: .
    command: celery -A email_validator worker --loglevel=info --concurrency=4
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - evnet

volumes:
  pgdata:

networks:
  evnet: